language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - master
rvm:
- 2.4
env:
  global:
    secure: fl2c/lbfWF2mfDt5yk6JW3M7p1zWLqDQCMioNG7SA1uhFhsPfspshhA90gF0TmdQ1cWLPDkbtVgLTcI3CWgwX9ipXrkB1+Th7aBJwA0w1d8LA4fZbTa0zhVsxph+xhwB0LDom/6rwhQaiEoWglAwzjobj8kxIkk9DiE0MBYEdD5p3kBgKD97tKtbpAjXGkLQ52I1pr0jB0sT+MHZEYyiCa8eijPdDI1dAK03oFzb73XNEUdnjiA/gi9fAK2PjyftyZF4dG3b5QokksrPjJkF7eoXaWK+VW5pejN3XwCGVGSqNhiFrFRWUyc9XzV+grkKLdO/mo+e/OdEayfMqtTOsFI6ucjog95V6aIdNVYg4Nqs6uhfHEiyxccbmEUX6GxvhKIherh9vdGzv0E9EdRr2Ix/OymlvTnPCKoXOhgfqlTk9qYwfV6uh0/7WX04myG8mWVQGKLM/UAN/j/vyWtbMbKU8CMLh8uRB6uYSb0ocbFwJY8TyPFsh63ryABqsPWi8uV+er9RHXVaFp+bXeQ3FCJWoRRd5Vl4M3HZLibC+zGdkDSfxP1WhJ72F4MJcIb86wIkGhAoOWyBHxQQrfp8xG0XoJ2qja5v33yvGN16qyurwWdjBHg8J4CkCsuhY9bLOAtSpu3d9N+CqCa+mjgu209Ol/y8gUWtNnN9LP8Aky0=
